---
version: "3.4"
services:
  pha:
    image: "uwcirg/medmorph-pha:${PHA_IMAGE_TAG:-develop}"
    build:
      context: .
    volumes:
      - ./:/opt/app
    ports:
      # allow override of published port
      - ${EXTERNAL_PORT:-5000}:5000
    env_file:
      - medmorph_pha.env
